### ISSUE TITLE
Missing instructions

### ISSUE THREAD

**Issue by gmelchett** [ttmo-O/x86-manpages#4]
Several instructions are missing man pages;
for example:

`push, pusha, pop,popa, les, lds, lss`

They are all present on Felix Cloutiers site, example pusha
[https://www.felixcloutier.com/x86/pusha:pushad](https://www.felixcloutier.com/x86/pusha:pushad)

**Comment by ghost** [comment]
Commit 048ae580712206247e1d4d0edc74a82d6d32fc2e resolves this issue.
